# Generated by Django 4.1 on 2022-09-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_orderitem_user_alter_orderitem_product_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
