# Generated by Django 4.1 on 2022-09-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_category_product_img_delete_orderitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='full_name',
        ),
    ]
