# Generated by Django 4.1 on 2022-09-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_rename_name_product_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='full_name',
            new_name='prod_name',
        ),
    ]
