# Generated by Django 4.1 on 2022-09-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_review_reviewimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewimage',
            name='review',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
