# Generated by Django 4.1 on 2022-09-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_remove_reviewimage_review_delete_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
