# Generated by Django 4.1 on 2022-09-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_product_extra_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='payments.product'),
        ),
    ]
