# Generated by Django 4.1 on 2022-09-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_price_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumOfNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.IntegerField()),
                ('n2', models.IntegerField()),
                ('sum', models.IntegerField()),
            ],
        ),
    ]
