# Generated by Django 4.1 on 2022-09-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_sumofnumbers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SumOfNumbers',
        ),
    ]
