# Generated by Django 4.1 on 2022-09-18 13:05

from django.db import migrations, models
import django.db.models.deletion
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_review_modified_review_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=general.models.nameFile)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='general.review')),
            ],
        ),
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
